### ISSUE TITLE
Comments aren't converted the right way

### ISSUE THREAD

**Issue by thomas-rager** [tj/styl#28]
I use the whitespace style

``` css
/* Selection background will be assigned to TD instead of TR, because IE8/9 does not support gradient for TRs */

.vclTable .vclSortableCol button.vclButtonStd:hover
  color: #333333
```

becomes: 

``` css
/* Selection background will be assigned to TD instead of TR, because IE*/

9 does not support gradient for TRs */;

.vclTable .vclSortableCol button.vclButtonStd:hover  {
  color: #333333;
}
```
